import { IUserRepository } from '../../domain/repositories/IUserRepository';
import { User } from '../../domain/entities/User';
import bcrypt from 'bcryptjs';

export class RegisterUser {
    constructor(private userRepository: IUserRepository) { }

    async execute(name: string, email: string, password: string): Promise<User> {
        const existingUser = await this.userRepository.findByEmail(email);
        if (existingUser) {
            throw new Error('User already exists');
        }

        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);

        const newUser = new User(
            '', // ID will be generated by DB
            name,
            email,
            hashedPassword
        );

        return await this.userRepository.save(newUser);
    }
}
